### ISSUE TITLE
Is S3 bucket mandatory?

### ISSUE THREAD

**Issue by toton6868** [ibi-group/datatools-ui#484]
I am using the following settings in `settings.yaml` file where I do not want to use S3 bucket thats why I used `use_s3_storage: false` and put a hash before s3bucket property
```
# Mastarm/deployment configuration properties. Note: application configuration
# is now taken entirely from server application (there are still some
# UI-specific env variables are in this repository's env.yml).
cloudfront: DEPLOY-DISTRIBUTION
entries:
  - 'lib/main.js:dist/index.js'
  - 'lib/index.css:dist/index.css'
use_s3_storage: false
#s3Bucket: bucket-name
```

I have done similar things in `server.yml`. here is the settings
```
application:
  client_assets_url: https://example.com
  shortcut_icon_url: https://d2tyb7byn1fef9.cloudfront.net/ibi-logo-original%402x.png
  public_url: http://10.10.10.161:9967
  notifications_enabled: true
  cors:
    enabled: false
    origins: http://10.10.10.161/
    methods:
    headers:
  port: 3104
  data:
    gtfs: /opt/gtfs/gtfs-storage
    use_s3_storage: false
    #s3_region: us-east-1
    #gtfs_s3_bucket: bucket-name
modules:
  dump:
    enabled: true
  enterprise:
    enabled: false
  deployment:
    enabled: true
  editor:
    enabled: true
    url: http://10.10.10.161:9001
  alerts:
    enabled: true
    use_extension: mtc
    url: /alerts
  sign_config:
    enabled: true
    use_extension: mtc
    url: /signs # eventually remove this
  user_admin:
    enabled: true
  # Enable GTFS+ module for testing purposes
  gtfsplus:
    enabled: true
  gtfsapi:
    enabled: true
    load_on_fetch: false
    # use_extension: mtc
    # update_frequency: 30 # in seconds

extensions:
  mtc:
    enabled: false
    rtd_api: http://localhost:9876/
    s3_bucket: bucket-name
    s3_prefix: waiting/
    s3_download_prefix: waiting/
  transitland:
    enabled: false
    api: https://transit.land/api/v1/feeds
  transitfeeds:
    enabled: false
    api: http://api.transitfeeds.com/v1/getFeeds
    key: your-api-key

```

When I am satring server through the following script the `datatools-server` starting successfully.

`java -jar target/dt-v3.2.0-551-g568af07.jar /opt/gtfs/datatools-server/configurations/default/env.yml /opt/gtfs/datatools-server/configurations/default/server.yml`

But when I am trying to start `datatools-ui` through `npm run deploy` the following error is occurring and no service is starting

```
> datatools-manager@0.0.0-development predeploy /opt/gtfs/datatools-ui
> yarn

yarn install v1.17.3
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.00s.

> datatools-manager@0.0.0-development deploy /opt/gtfs/datatools-ui
> mastarm deploy --minify --env production

🚧 *deploying: datatools-manager@4af00b by <@ubuntu>*
🚦 *mastarm:* v5.1.3
☁️ *cloudfront:* DEPLOY-DISTRIBUTION
#️⃣ *commit:* 4af00b7c61eb66731c22f1b3d7bbc8c30d5da695
🌱 *env:* production
🗜️ *minify:* true
📦 *s3bucket:* undefined
🛠️ *building:* lib/main.js, lib/index.css
🚀 *uploading:* 4 file(s)
🚨 *datatools-manager@4af00b error deploying datatools-manager@4af00b s3 upload to undefined/dist/index.css.map rejected with MissingRequiredParameter Missing required key 'Bucket' in params*
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! datatools-manager@0.0.0-development deploy: `mastarm deploy --minify --env production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the datatools-manager@0.0.0-development deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2019-09-22T11_39_30_759Z-debug.log

```
